### ISSUE TITLE
fst-bin: `--tmp-dir` is a flag

### ISSUE THREAD

**Issue by Anhil-111** [BurntSushi/fst#111]
I don't think it's supposed to be a flag, considering you are calling `value_of_os` on it here: https://github.com/BurntSushi/fst/blob/17bbc05c914d648b7346a12838ecdc21f67c76e1/fst-bin/src/cmd/set.rs#L44.

**Comment by BurntSushi** [comment]
Huh? I don't understand what the problem is. Could you please explain more?

**Comment by Anhil-111** [comment]
Sorry, should've elaborated a bit. It does not accept a value, needs either `takes_value(true)` or a default value (since that's what worked for `batch-size`, `fd-limit` and `threads`)

**Comment by BurntSushi** [comment]
Okay. PRs are welcome to fix it if you need that functionality.

**Comment by Anhil-111** [comment]
Yeah, discovered it because I had to use an external drive.
