### ISSUE TITLE
Get the identifier for a key to use as a reference

### ISSUE THREAD

**Issue by pawelurbanski** [BurntSushi/fst#114]
Hi Everyone,
FST is a fantastic library and at the same time very specialized. I am considering it for a project while learning Rust.
Considering the following case, what would be the best way to get the desired solution?

* FST is a dictionary of names of objects,
* The key's value holds an integer as a flag,
* The algorithm needs to point back at the key when doing a reverse lookup.

Is it possible to do the following?

* Build the FST - it is static and occasionally rebuilt,
* For every key get some kind of internal identifier,
* Build another FST with values pointing at particular keys in the first FST.

I want to use the second FST to find a set of keys, then using their values being pointers to keys in the first FST, get the keys by the pointer value.
This identifier can be used for some key-value storage for more metadata as well. The identifier is the key for the metadata lookups.
We get the single dictionary or a map with possible mappings - it is similar in concept as facts and dimensions tables in data warehouses.

Thank you for any hints in the right direction.

**Comment by BurntSushi** [comment]
There are only two ways to get a key value:

1. [Search for it.](https://docs.rs/fst/0.4.4/fst/raw/struct.Fst.html#method.search) Or similarly, execute a [range query](https://docs.rs/fst/0.4.4/fst/raw/struct.Fst.html#method.range).
2. In the special case where your values are monotonically increasing, you can [find the key for a specific value](https://docs.rs/fst/0.4.4/fst/raw/struct.Fst.html#method.get_key).
