### ISSUE TITLE
Fst::as_ref to borrow underlying data

### ISSUE THREAD

**Issue by Nemo157** [BurntSushi/fst#116]
It would be nice to be able to borrow access to the underlying data, to allow doing stuff that requires access at the known generic type `D`.

```rust
impl<D> Fst<D> {
    pub fn as_ref(&self) -> &D {
        &self.data
    }
}
```

**Comment by BurntSushi** [comment]
Sounds good, although I'd probably prefer using the name `as_inner` instead to mirror the `into_inner` method. PRs are welcome.
