### ISSUE TITLE
Is it possible to add metadata to the FST?

### ISSUE THREAD

**Issue by isubasinghe** [BurntSushi/fst#120]
I would like to map strings to a struct. At the moment there isnt a way to do this, is my understanding. 
I was just wondering if there is way to add this functionality?

```rust
pub struct Node {
  word: String,
  metadata: MetaData
}

pub struct MetaData {
// blah blah blah
}

impl AsRef<[u8]> for Node {
    fn as_ref(&self) -> &[u8] {
        self.word.as_ref()
    }
}
```

Why I want this functionality? Well it would be quite easy to add a vector of document id's in which words appear in in the metadata, I can implement a really efficient inverted index this way. 

I want to be able to do a search_with_state with a query and obtain the documents a word appeared in along with its BM25 score. 

Apoligies if this is dumb question, this is my first project with Rust.

**I believe I actually need to use the raw fst and not the Set.** 
**Is this correct?**

I'd be happy to implement a generic Set and create a PR if you'd like too.

Thanks so much for this library and the work you've done. :))

**Comment by BurntSushi** [comment]
Please read my blog post on FSTs: https://blog.burntsushi.net/transducers/

It's not like I arbitrarily chose the restrictions you're running into. They are a fundamental limitation of the technique.

There isn't much mystery here. The only power you have exposed by this crate is the ability to map a sorted sequence of byte sequences to u64 values. If you need more complex values, then you'll need to implement additional structures. An FST is just one small component of an IR engine. There's a lot more to build.

**Comment by isubasinghe** [comment]
Thanks for your quick response.

Yeah I did have a read of that blog but unfortunately not of the paper you are referring to in it yet. I was just curious if the accept states could have metadata in there somehow..  But if not, I guess I'll have to figure out another way somehow. 

I'll close this issue now, thanks for your help

**Comment by BurntSushi** [comment]
Usually people use the u64 value as an offset into another memory mapped file.

**Comment by BurntSushi** [comment]
And I don't think you necessarily need to read the underlying paper, although it is of course quite interesting!

**Comment by isubasinghe** [comment]
Ah awesome, thanks, I think I may go with just the u64 as an offset then.
