### ISSUE TITLE
Generic FST outputs

### ISSUE THREAD

**Issue by tapeinosyne** [BurntSushi/fst#124]
First off, thanks for creating and maintaining this crate! It has proved itself an outstanding tool for dealing with large data sets on my old, RAM-limited machine.

As for the issue, I have two small use cases where I would like an output other than u64. (Specifically `char` and `u16` or `u32`.) The documentation [mentions](https://docs.rs/fst/0.4.5/fst/raw/struct.Output.html) that generic output types are a possibility for future versions of `fst`, and I'd like to see them implemented.

Would you be willing to accept PRs working towards that goal?

**Comment by BurntSushi** [comment]
See https://github.com/BurntSushi/fst/pull/21 and https://github.com/BurntSushi/fst/issues/90

In short, no, I would be unlikely to accept such a change. Moreover, in your case, the change wouldn't buy you much relative to the complexity of the change itself. Both a `char` and a `u16` can be represented by a `u64`. Such a generalization is much more useful for things too big to fit into a `u64`.
