### ISSUE TITLE
MmapReadOnly::as_slice() does not take in account offset and len

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#14]
`as_slice()` returns the whole byte array.

Should not it take in account `offset` and `len`?

**Comment by fulmicoton** [comment]
I see this has been solved in master. Thanks. Could you publish it to crates?

**Comment by BurntSushi** [comment]
@fulmicoton Ah right, sorry about that! I've just uploaded `0.1.31` to crates.io. Thanks!

**Comment by fulmicoton** [comment]
Awesome thanks
