### ISSUE TITLE
provide reverse mapping from value to key in some cases

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#16]
It is sometimes useful to have `String <-> StringOrdinal` mapping, where `StringOrdinal` is its position within the set of strings assuming the strings have been sorted.

The fst repo makes a very good `String -> StringOrdinal` mapping. 
Wouldn't it be possible to get the `StringOrdinal -> String` by binary searching the correct transition at each node?

**Comment by BurntSushi** [comment]
I am pretty sure the reverse mapping is possible to get, but I haven't given it much thought. Your idea sounds plausible at first glance.

**Comment by fulmicoton** [comment]
I wonder how recent version of lucene do it...

**Comment by fulmicoton** [comment]
Even if the field is index, `DocValues` do not rely on the term dictionary for the `ordinal -> string` mapping. Instead, it has an  uncompressed storage facility, or a classically compressed storage.

**Comment by fulmicoton** [comment]
I was able to implement something like directly with the current public API. This does not need to be part of the fst crate.

**Comment by PSeitz** [comment]
@fulmicoton a reference to the solution would be nice

**Comment by fulmicoton** [comment]
@PSeitz 

My code looks like this:

```
fn ord_to_term(fst: &Fst, mut ord: TermOrdinal, bytes: &mut Vec<u8>) -> bool {
    bytes.clear();
    let mut node = fst.root();
    while ord != 0 || !node.is_final() {
        let transition_opt = node.transitions()
            .take_while(|transition| transition.out.value() <= ord)
            .last();
        if let Some(transition) = transition_opt {
            ord -= transition.out.value();
            bytes.push(transition.inp);
            let new_node_addr = transition.addr;
            node = fst.node(new_node_addr);
        } else {
            return false;
        }
    }
    true
}
```

**Comment by BurntSushi** [comment]
I'm not sure why this was closed, but this is definitely something I'd like to have in the API. Especially if the implementation is really as simple as above.

**Comment by fulmicoton** [comment]
@BurntSushi After reading the description of this feature in your PR, I would like to make sure that  there are no misunderstanding here. Maybe it was better explained in #48.

The snippet above only makes sense **if the value associated to the string are monotonic**. 

Making it into the API therefore is a tiny bit difficult because of the implicit contract. Of course, one could argue that binary search exists in the standard library and has the same implicit contract, but `binary_search` is 
- well known
- has a contract that is easier to express
- is super useful.

One thing that could be in the API, is a wrapper over `fst::Map`, that could be called `Lexicon` for instance, in which the value associated to each key is the ordinal of the key.

The `Lexicon` would get the same API as the map, except for this extra `ord_to_key` method, and 
insert would only take a `key: &[u8]`.

**Comment by BurntSushi** [comment]
I think I'm generally fine with declaring this routine as only useful if the values satisfy monotonicity. To make its lower level nature clear, we can put it on the `Fst` type but not `Set` or `Map`.

`Lexicon` is a neat idea, but it's a lot of ceremony... It also takes away control of what the values are. They might be monotonic increasing but discontiguous, which I believe still works fine.
