### ISSUE TITLE
how map works ?

### ISSUE THREAD

**Issue by setop** [BurntSushi/fst#166]
I do `fst map <({ echo foo,1 ; echo bar,2 ; echo baz,3 ;  }) a.fst`.
Then `fst fuzzy a.fst bir`.
I get `bar` but not `2`.
What do I miss ?

**Comment by BurntSushi** [comment]
Have you looked at `fst map --help`? It documents a `-o/--outputs` flag.

**Comment by BurntSushi** [comment]
I typed `fst map --help`, but I meant `fst fuzzy --help`. It's there:

```
$ fst fuzzy --help | rg outputs
    -o, --outputs    When set, output values are shown as CSV data.
```
