### ISSUE TITLE
Expose the number of bytes written so far by the MapBuilder

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#23]
I would like to be able to know how much have been written in the underlying Writer of the Fst map builder.

My use case is as follows :

I want to read a dictionary that is both large, and only accessible via a distributed file system
(think S3, HDFS, etc.)
The filesystem allow for random reads, but each reads has a great latency (~100 ms). Bandwidth is ok (~10MB/s). Downloading the whole thing locally is not an option.

I would rather avoid hashing my dictionary first, because it will make sorted iteration impossible.
Changing the abstraction for the data is not a solution either because I would still suffer from locality. I would like to add items to the dictionary, and when I have written 1MB, close the builder and open a new one...
The index leading to the correct K, V chunk will itself be a fst (or rather a tree of fst).

Would you accept pull request ?

**Comment by BurntSushi** [comment]
Yes, this seems fine to me. I think the count is actually tracked internally as well.

An alternative implementation path is to use your own `Write` implementation that counts bytes. The only thing missing then is getting borrowed access to your writer through the `Builder` API, which I think would also be a reasonable addition. (The standard library tends to define `get_ref` and `get_mut`, in addition to the `into_inner` that we already have.)

Having all of `bytes_written`, `get_ref` and `get_mut` sounds reasonable actually.

**Comment by fulmicoton** [comment]
The trouble really is the borrowed access...

Come to think of it, I need an access after each `insert` calls, but also after finish so I will definitely have to wrap my own counting writer.

`.get_ref` is probably what I want here.

**Comment by BurntSushi** [comment]
Access to `bytes_written` after each `insert` call should be fine, but indeed, if you need it after `finish`, then it will need to be a property on your own `Write` impl.

**Comment by fulmicoton** [comment]
Thanks for addressing this issue and sorry for not having done it myself earlier.
