### ISSUE TITLE
Collation of string sort?

### ISSUE THREAD

**Issue by davidblewett** [BurntSushi/fst#26]
Can you elaborate what collation order is used by this library? I was loading data into a `Set` that was retrieved from PostgreSQL, and was ordered by the `en_US` collation ( see https://www.postgresql.org/docs/current/static/collation.html )  and got the `OutOfOrder` error. My database is configured to use UTF8 encoding and en_US collation.

For example:

```sql
example=# select * from (values ('aabbcc.exe'), ('{12345-345324}.sys')) foo order by column1 COLLATE "en_US";
      column1       
--------------------
 {12345-345324}.sys
 aabbcc.exe
(2 rows)

example=# select * from (values ('aabbcc.exe'), ('{12345-345324}.sys')) foo order by column1 COLLATE "C";
      column1       
--------------------
 aabbcc.exe
 {12345-345324}.sys
(2 rows)
```

It appears that this library uses `C` collation. Can it check the environment to see what order it should use, or will it always need to use `C`? If the latter, I can change my Postgres query to specify the collation to sort by, but it would be much preferable if this library could use the collation defined in the environment (i.e. `LANG=en_US.UTF-8`).

**Comment by BurntSushi** [comment]
The only possible choice is the order already specified by this library: lexicographic. The ordering is determined by construction of the automaton, which is byte oriented and completely unaware of any specific encoding. The `C` collation order does indeed correspond to this.
