### ISSUE TITLE
Keys with a value of zero may return wrong output

### ISSUE THREAD

**Issue by tapeinosyne** [BurntSushi/fst#35]
It seems that keys associated to `Output::zero()` may return the wrong value; specifically, a zero-value key will emit the output of the longest non-zero-value key within its prefix.

Here is a test for a (nearly) minimal failure case which illustrates the problem:

```rust
#[test]
fn suffix_to_zero() {
    use std::collections::BTreeMap;
    let pairs = &[("a", Output::new(1)), ("ab", Output::new(0)), ("abc", Output::new(0))];
    let btree : BTreeMap<&str, Output> = pairs.iter().cloned().collect();
    let mut builder = raw::Builder::memory();
    builder.extend_iter(btree.clone());
    let fst = Fst::from_bytes(builder.into_inner().unwrap()).unwrap();

    let from_btree = btree.get("abc").cloned();  // Output(0), correct
    let from_fst = fst.get("abc");               // Output(1), wrong
    assert!(from_fst == from_btree);
}
```

Looking up either `"ab"` or `"abc"` in the raw FST will return `1` instead of `0`, suggesting that their paths are polluted by the shared prefix "a". Presumably this [`if`](https://github.com/BurntSushi/fst/blob/58cc1fa9caed8b4c3b334ab552d88890e5eca51b/src/raw/build.rs#L218) is the culprit.

I'll see if I can work out a fix later today.

**Comment by BurntSushi** [comment]
@tapeinosyne Thank you for reporting this. That was an excellent diagnosis and made it much easier for me to fix. The fallout here is that every insert into a map---even if the output is zero---requires handling the output values, which actually seems fine to me. The hit is not applied to sets. The commit message in https://github.com/BurntSushi/fst/commit/32fc82ba953a93ff2cae78be5d78595078c67193 explains.

**Comment by BurntSushi** [comment]
This is on crates.io in `fst 0.1.38`.
