### ISSUE TITLE
Article mentiones a "fst" command-line tool, but `cargo install` fails for it.

### ISSUE THREAD

**Issue by vi** [BurntSushi/fst#39]
```
$ cargo install fst
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading fst v0.1.38
  Installing fst v0.1.38
error: specified package has no binaries
```

I expect it to deliver the same tool as in [the article](http://blog.burntsushi.net/transducers/).

**Comment by BurntSushi** [comment]
`fst` is the library. The blog includes a section on how to get it: http://blog.burntsushi.net/transducers/#how-to-get-it --- Did you try that? Does it not work?

**Comment by vi** [comment]
I hasn't tried it yet (it is mentioned lower in the article compared to where I am reading now). Second try works:

```
$ cargo install fst-bin
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading fst-bin v0.1.2
  Installing fst-bin v0.1.2
 Downloading csv v0.14.7
...
   Compiling fst-bin v0.1.2
    Finished release [optimized + debuginfo] target(s) in 170.23 secs
  Installing /home/vi/.cargo/bin/fst
$ fst --help
Usage:
    fst <command> [<args>...]
    fst --help
    fst --version

Commands:
    csv     Emit statistics about nodes or edges.
    dot     Emit a dot representation of an FST.
    dupes   Emit diagnostic info about frequency of duplicate nodes.
    fuzzy   Run fuzzy queries based on edit distance.
    grep    Search an FST with a regex.
    map     Create a new map of key-value pairs.
    node    Show a single node.
    range   Run range queries.
    rust    Emit a Rust source code for this FST.
    set     Create a new set of keys.
    union   Union two or more FSTs.

Options:
    -h, --help     Show this help message.
    -v, --version  Show version.
```

Maybe the fact that it's `fst-bin`, not just `fst` should be mentioned early in the article, in "Teaser"? Or the binary itself can be renamed from `fst` to `fst-bin`?

**Comment by BurntSushi** [comment]
> Or the binary itself can be renamed from fst to fst-bin?

That's not happening, sorry.

Also note that the instructions don't actually say to use `cargo install fst-bin`. They ask you to clone the repo. In an ideal world, I would be good about always updating the `fst-bin` crate, but in reality, that might not be so. In contrast, cloning the repo and building `fst-bin` manually will always do the right thing.
