### ISSUE TITLE
Documentation about Streamer/IntoStreamer may mention Associated Type Constructors more early/clearly

### ISSUE THREAD

**Issue by vi** [BurntSushi/fst#40]
1. There should be a link to [this][1].
2. The intro sentence `Streamer describes a "streaming iterator."` may be changed to note that it is a workaround, not a proper trait.

"1." and "2." may actually be combined: "`Streamer` is a workaround for a "streaming iterator", which can't be done properly without [Associated Type Constructors][1]."

[1]:https://github.com/withoutboats/rfcs/blob/associated_hkts/0000-friends_in_high_kindednesses.md

**Comment by BurntSushi** [comment]
Sorry for responding to this so late, but I'm not sure I really agree with this. It's almost three years later and ATCs aren't yet a thing. (And your link is dead.) I think if you read the full docs on the trait, it should be clear that the situation isn't ideal. So I'm going to leave it mostly as is for now.
