### ISSUE TITLE
Should fst::Automaton::start be changed to an associated constant?

### ISSUE THREAD

**Issue by Eh2406** [BurntSushi/fst#44]
The documentation claims "This method should always return the same value for each implementation." Which sounds like the prime case of associated constants. So at some point in the future, when a new release of this crate comes out that does not support pre 1.20 rust, does it make sense to change it to a constant?

**Comment by vorner** [comment]
I don't think that is a good idea. That would prevent using anything that is not const-constructible from being the `State`.

A stupid example: I want to match anything that has at least one of each `!`, `@`, `#`. Now I can do this:

```rust
struct Automaton;

impl Automaton {
  type State = HashSet<u8>;
  fn start() -> Self::State {
    vec![b'!', b'@', b'#'].into_iterator().collect()
  }
  ...
}
```

While this does return the same thing, it needs to be constructed at runtime. Surely there are other ways to accomplish the goal here, but…

**Comment by BurntSushi** [comment]
Agreed. We could maybe get away with an associated const, but I think it adds too much restriction without a commensurate increase in benefit.
