### ISSUE TITLE
Update the levenshtein construction algorithm

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#47]
I implemented the method used in [Fast String Correction with Levenshtein-Automata](http://lml.bas.bg/~stoyan/levaut6.ps.gz). 
Currently the project is available here. https://github.com/tantivy-search/levenshtein-automata

Building a new automaton requires to precompute a datastructure for each type of Levenshtein automaton considered. This precomputation is rather slow, but is typically amortized after building one automaton. If this is a problem, it is also possible to serialize it and ship it with the library. That's the approach taken by Lucene.

The benefits compared with the current implementation of fst-levenshtein are as follows
- building a DFA is much faster. For instance for a distance of 2, and for the string "Levenshtein",
the current algorithm takes `2.5ms` while the new implementation takes `0.09ms`. Note that clearly `2.5ms` is fast enough for most application, and fst intersection will dominate anyway.

- the produced DFA is smaller, so we can hope for less cache miss. (!?)
Microbenchmarking this with honesty is obviously very difficult... Going through the DFA above
over the string `Leventshtein` went from `72 ns` to `8 ns`. The difference might also be due to 
the interface being easier to deal with for the compiler (state are `u32` that I pass by value).
For a levenshtein distance of 2 without transposition, the number of states for the DFA (before utf8 conversion) is bounded to `30 x (query len + 1)`

- the DFA outputs the actual distance rather than a boolean. This is useful for scoring.

- Optionally transposition can be given a cost of 1 (Levenshtein-Damerau).
- It addresses #38

The Cons as I see it are:
- It is yet an extra crate
- Code quality is not as good as yours and bugs might be lurking somewhere.

Should we switch to this implementation and how do we proceed ?

If you decide to go with this implementation, the way I see it is : I should publish the project as a different crate. This sucks to have to have two repo for levenshtein automaton, but currently `fst_levenshtein` cannot be used without depending on `fst` which is not idea either.
`fst_levenshtein` could depend on this library and wrap its DFA.

An alternative solution, would be to integrate my code into the `fst_levenshtein` crate...

**Comment by BurntSushi** [comment]
Woohoo! Nice work!

> An alternative solution, would be to integrate my code into the fst_levenshtein crate...

I think this is the ideal path, right? I think the only real requirement is that it implements the `Streamer` trait?

I think the biggest impediment to making this happen is actually getting the code reviewed and merged. At a minimum, I would like to see the code quality and tests *better* than what the `fst-levenshtein` crate has right now.

**Comment by BurntSushi** [comment]
> fst_levenshtein could depend on this library and wrap its DFA.

Oh I see, I missed this path. I'd be OK with this too.

How are you currently using your crate if it doesn't depend on `fst`? (And therefore doesn't implement `Streamer`.)

**Comment by fulmicoton** [comment]
> I think this is the ideal path, right? I think the only real requirement is that it implements the Streamer trait?

I am confused, you really meant `Streamer` here, not `fst::Automaton` ?

> How** are you currently using your crate if it doesn't depend on fst? (And therefore doesn't implement Streamer.).

I am confused by the question, so my answer might be off. (Again, did you mean `fst::Automaton`?)

Right now I am not using it at all. I intend to focus on making a good autocomplete service out of tantivy in 0.6.0, so I implemented this algorithm as a preliminary work.

I will probably to have it implement `fst::Automaton` at one point, yes...

Note that I may have to rewrite intersection because I might need to have access to that actual distance of each term in the dictionary.

**Comment by PSeitz** [comment]
Any updates on this? Would be really nice to have this integrated into the fst crate.

**Comment by BurntSushi** [comment]
> Any updates on this?

If there's an update, then you'll see it in this issue. There's no need to ask.

**Comment by fulmicoton** [comment]
> There's no need to ask.

Well it has some benefits. For instance it's always good to know someone else is interested in this.
If no one is interest, I can just keep the code independent.

@PSeitz Here is information that could interest you and that was not documented in this issue:

## In the meanwhile, you can actually use it already, provided you point at the [github project](https://github.com/tantivy-search/levenshtein-automata).

The repo has still not been published as a crate, but the master branch now implements `fst::Automaton` if you use the `fst_automaton` feature flag, so you can already use it with `fst`.

## You will probably be able to access the levenshtein distance in the future

In [`#60`](https://github.com/BurntSushi/fst/issues/60) we discussed if I could add an API  to get a KV `Stream` which also gives access to the automaton state. I think I have all the information I need there
to start working.


## What about the future of these two crates?

Ideally, improving the `fst-levenshtein` crate is probably the least confusing for the community.

Unfortunately, to get there, there are many tricky decisions to be taken, I cannot reasonably commit my time working on this without discussing them and getting a "green light" from @BurntSushi ... I am quite busy nowadays and I can only imagine how busy @BurntSushi is.

Most of these decisions revolve around the fact that the `better` algorithm requires a precomputed structure for each levenshtein distance.
The current API is not very friendly with this idea. One approach could be to ship it as a `static &[u8]` for distance `1,2, and maybe 3, 4`and refusing building automaton above these distance ; which means breaking public API. We could keep the current code for distance above these distance. We could not ship the structure but cache it in a `lazy_static HashMap`.

I could be wrong, but there are good chances that this ticket will be abandonned. 

In that case, I will publish the levenshtein-automata crate and the two crates will just end up living their lives independently.

**Comment by BurntSushi** [comment]
@fulmicoton Thanks for the write up! Yeah, I just don't have the time to dedicate to this, so I think having two crates is just fine. I think both the `fst-levenshtein` and `fst-regex` crates are just prototypes at this point, so I'd say we're well within the "let's experiment and see what works" stage.

**Comment by PSeitz** [comment]
@fulmicoton Thanks for the info, so it's already working with the fst crate, that's great!

> Ideally, improving the fst-levenshtein crate is probably the least confusing for the community.

Yes ideally, but I also wouldn't mind having two crates. A link to the crate at some point in the future could be enough.

> One approach could be to ship it as a static &[u8] for distance 1,2, and maybe 3, 4and refusing building automaton above these distance ; which means breaking public API.

Currently we have the 10k state limit, which probably already kicks in with distances around 4. Having more reliability here would imho be an improvement of the API.

https://github.com/BurntSushi/fst/blob/16dd91b8143e01c605afbb4f7ae484f657e6184b/fst-levenshtein/src/lib.rs#L17

**Comment by fulmicoton** [comment]
Oh... I didn't know about that limit.

For reference, here is the number of state of the parametric dfa (the one that is independent from the query and can be cached, or serialized with the lib.)

| dist   |  num of states  |  num of transitions |  Estimated serialized size |
| ------ | ------------------------- |-----------------------------|-----------------------|
| 1      |  6                           | 2^3 = 8                       | 150 bytes          | 
| 2       | 31                          | 2^5 = 32                     | 3KB                   |
| 3       | 197                        | 2^7 = 128                   | 75KB                 |
| 4       | 1354                      | 2^9 = 512                   | 2MB                  |

With transposition

| dist   |  num of states  |  Number of transitions |   Estimated serialized size | 
| ------------- | ------------------------- |-------------------|------------------------------------|
| 1               |  8                           | 2^3 = 8          |  200 bytes                          |
| 2               |  68                          | 2^5 = 32       |  6.5 KB                               |
| 3               |  769                        | 2^7 = 128     | 300KB                                |
| 4               |  9628                      | 2^9 = 512     | 15 MB                                |

**Comment by BurntSushi** [comment]
I don't think I'll have time to look into this myself, but if someone wants to improve the existing `fst-levenshtein` crate, then I'd be very happy to look at a PR.
