### ISSUE TITLE
Serialization support?

### ISSUE THREAD

**Issue by pacman82** [BurntSushi/fst#52]
Is there any plan to support serialization via `serde` for `fst::Map`? If not what is the best (fastest) way to recreate a `Map` from persistent data?

**Comment by BurntSushi** [comment]
@pacman82 Please describe the problem you're trying to solve. The FST itself always lives in its serialized form. That is, there is no distinct between a serialized FST and a deserialized FST. (That's kind of the point of this crate in the first place. You can memory map an FST from disk that is bigger than the amount of RAM on your machine, and the OS will take care of paging it in and out of memory for you.)

**Comment by pacman82** [comment]
@BurntSushi Thank you for your quick response. Sorry, it did take me so long to answer. I want to run queries on the `Map` from within a python flask web service (which already exists). Currently all the other state in this web service is serialized from and to a redis cache. Yet your answer made me realize I should probably just `MapBuilder` and create a file, instead of using `from_iter` to create a `Map`. Thanks a lot. Consider this question answered.

**Comment by BurntSushi** [comment]
@pacman82 I see. If you really wanted to, you could stick the FST in a redis cache as a binary blob as is. Then you can [build a `Map` from a `Vec<u8>` on the heap](https://docs.rs/fst/0.3.0/fst/struct.Map.html#method.from_bytes). This is fine if your FST is relatively small. But there is also no problem with just putting it on disk and [memory mapping it](https://docs.rs/fst/0.3.0/fst/struct.Map.html#method.from_path).

**Comment by jbaiter** [comment]
> Yet your answer made me realize I should probably just MapBuilder and create a file, instead of using from_iter to create a Map. Thanks a lot. Consider this question answered.

FWIW, if you're using the Python bindings, `from_iter` takes a `path` keyword argument that directly creates the FST on disk.

**Comment by pacman82** [comment]
@jbaiter Thanks. This might prove useful. As it currently stands I am trying to convince my colleagues to allow a Rust Server. We already have some Rust in production, so maybe I'll be successful.
