### ISSUE TITLE
is this library byte based or character based?

### ISSUE THREAD

**Issue by WarpspeedSCP** [BurntSushi/fst#53]
I'm asking, because, utf8. Thank you very much for this library; I'm planning on using it as an autocompleter for a fancy calculator app.

**Comment by BurntSushi** [comment]
Have you read the documentation? If so, could you please point out why the answer to your question isn't clear?

**Comment by BurntSushi** [comment]
See also: http://blog.burntsushi.net/transducers/

**Comment by WarpspeedSCP** [comment]
Ah, I haven't gotten around to it, sorry.

**Comment by BurntSushi** [comment]
OK, then this issue isn't actionable. Please let me know how the documentation could be improved.
