### ISSUE TITLE
fst_levenshtein 0.3.0 not on cargo

### ISSUE THREAD

**Issue by thomas-jeepe** [BurntSushi/fst#55]
Can you post the 0.3 version to cargo?

**Comment by BurntSushi** [comment]
Huh? The latest version of `fst-levenshtein` is on crates.io. The latest version is `0.2`, not `0.3`.

What problem are you trying to solve?

**Comment by newtack** [comment]
When you look at the main page (https://github.com/BurntSushi/fst) it shows next to the fst-levenshtein folder "0.3.0". This makes it look like fst-levenstein should be 0.3.0 as well.

**Comment by thomas-jeepe** [comment]
I tried running the example on main page and ran into compiler errors. Also, as newtack mentioned, it seemed that fst-levenshtein is 0.3.0.

**Comment by BurntSushi** [comment]
Thanks! I fixed the compilation errors and noted what should go in your `Cargo.toml` for the example in the README to work.
