### ISSUE TITLE
Return the automaton state with the `(key, value)`

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#60]
In some cases it can be useful to know the automaton state as well, when intersecting the fst with an automaton using `.search(...)`.

For instance, levenshtein's automaton's state hold the actual levenshtein distance of the current `key`. It is a very valuable information that could be used for ranking the results for instance.

**Comment by BurntSushi** [comment]
Could you please state more explicitly what API changes your requesting? Please include any relevant changes in the public API documentation.

(I'm asking because this is the easiest way for me to understand the feature request.)

**Comment by BurntSushi** [comment]
@fulmicoton I think that seems reasonable to me!

**Comment by MartinKavik** [comment]
Hey guys, I'm writing a search library and I want to use `fst` for fuzzy search, but I can't compute the correct score because I can't get distances for keys.
So.. is there a way how to get them now or we have to implement the API suggested above? Can I help somehow?
Thank you!

**Comment by BurntSushi** [comment]
@MartinKavik I think submitting a PR with the above API might be a good start.
