### ISSUE TITLE
Map a Streamer with a generic type

### ISSUE THREAD

**Issue by Kerollmops** [BurntSushi/fst#62]
I am currently working on an improvement of the `fst` library and I am facing a problem, I read the [Streamer Trait explanation](https://docs.rs/fst/0.3.0/fst/trait.Streamer.html) and the whole [lifetime nomicon explanations](https://doc.rust-lang.org/nomicon/hrtb.html) to try to fix this lifetime problem.

```rust
struct StreamWithStateOutput<S>(S);

impl<'a, S, T> Streamer<'a> for StreamWithStateOutput<S>
where
    S: Streamer<'a, Item=(&'a [u8], u64, T)>,
{
    type Item = (&'a [u8], raw::Output, T);

    fn next(&'a mut self) -> Option<Self::Item> {
        self.0.next().map(|(k, v, s)| (k, raw::Output::new(v), s))
    }
}
```

This is the current mapping struct that I produced to map a `Streamer` into another `Streamer` but that produce `raw::Output`s rather than `u64` (like the [`StreamOutput` struct you already define](https://github.com/Kerollmops/fst/blob/8ae8cf89fd8ca1fba7631437c6eaa418be4319bd/src/map.rs#L1087)) but I'm facing a problem of lifetime (like the one you talk about in the `Streamer` Trait documentation I suppose).

If I follow the help message that `rustc` outputs, I add a lifetime constraint `T: 'a` to the `StreamWithStateOutput` `Streamer` implementation and the problem comes after: the [`OpWithStateBuilder`](https://github.com/Kerollmops/fst/blob/8ae8cf89fd8ca1fba7631437c6eaa418be4319bd/src/map.rs#L1100) need a `T: 'static` constraint.

So I didn't add this constraint because it blocks everything above, the code is less fexible.
I just want to understand the problem here, it's hard to work with lifetimes 😢.

I also think of using `IntoStreamer` to construct a `StreamWithStateOutput`, like you said in the `Streamer` explanations but it's not possible I fear.

Note that I successfully [defined a `raw::OpWithStateBuilder` without forcing a `'static` bound on `T`](https://github.com/Kerollmops/fst/blob/op-builder-with-state/src/raw/ops.rs#L455) by using [the same constraints on the `push` method](https://github.com/Kerollmops/fst/blob/8ae8cf89fd8ca1fba7631437c6eaa418be4319bd/src/raw/ops.rs#L469-L475) than [the ones on `OpWithStateBuilder` (not `raw`)](https://github.com/Kerollmops/fst/blob/8ae8cf89fd8ca1fba7631437c6eaa418be4319bd/src/map.rs#L1114-L1120), the only thing that is different is [the `StreamWithStateOutput` mapping struct](https://github.com/Kerollmops/fst/blob/8ae8cf89fd8ca1fba7631437c6eaa418be4319bd/src/map.rs#L1140-L1151) (used to pass from a `u64` to an `Output`).

**Comment by BurntSushi** [comment]
Sorry, but I don't have the context necessary to answer this question, and rebuilding that context will take time that I won't have in quite some times. So I'm afraid you're on your own here.

It wouldn't surprise me if the `Streamer` approach I used is wrong, and that you might consider other approaches. You might consider this approach for example: https://docs.rs/streaming-iterator/0.1.4/streaming_iterator/

The problem here isn't necessarily lifetimes themselves, but rather that Rust doesn't really support higher-kinded polymorphism. It is possible that ATC (associated type constructors) will help resolve this, but AFAIK they are still a long way off.

**Comment by BurntSushi** [comment]
Revisiting this, I don't see myself doing anything in this space for quite some time. Perhaps not until associated type constructors are added to the language. Once they exist, I think it will open up the design space quite a bit more.
