### ISSUE TITLE
streamer range selection is inconsistent

### ISSUE THREAD

**Issue by yoursvivek** [BurntSushi/fst#73]
Consider following code, second and third asserts are not giving expected results.

```rust
// cargo-deps: fst="*"
extern crate fst;

use fst::{IntoStreamer, Streamer, Map};

fn main() {
    let map = Map::from_iter(vec![
        ([0, 0, 1], 1),
        ([0, 1, 1], 2),
        ([1, 2, 1], 3),
        ([1, 4, 1], 4),
        ([2, 4, 1], 5),
    ]).unwrap();
    let mut count = 0;

    let mut stream = map.range().ge(&[1, 2]).le(&[1, 3]).into_stream();
    while let Some((_, _)) = stream.next() {
        count += 1;
    }
    assert_eq!(count, 1);

    count = 0;
    let mut stream = map.range().ge(&[1, 2]).le(&[1, 2]).into_stream();
    while let Some((_, _)) = stream.next() {
        count += 1;
    }
    assert_eq!(count, 1); // assert fails; gives count == 0; why??

    count = 0;
    let mut stream = map.range().ge(&[1]).le(&[1]).into_stream();
    while let Some((_, _)) = stream.next() {
        count += 1;
    }
    assert_eq!(count, 2); // // assert fails; gives count == 0; why??
}
```

**Comment by BurntSushi** [comment]
I don't understand why you think your results are inconsistent. `ge(x).le(x)` will only give you keys that are exactly equivalent to `x`, and you have no keys equivalent to `[1, 2]` or `[1]`.

**Comment by yoursvivek** [comment]
Ok, how are comparison operation define here?
From first assert `[1, 2]` <= `[1, 2, 1]` <= `[1, 3]`. Similarly, we can also do `[1, 1]` <= `[1, 2, 1]` <= `[1, 2]`. So shouldn't `[1, 2]`  match `[1, 2, 1]`? At least that's what I inferred. I understand that in regular code arrays of unequal size can't be compared.

Wasn't the intent here to get a prefix match?

**Comment by BurntSushi** [comment]
> Ok, how are comparison operation define here?

Lexicographic ordering.

> `[1, 2] <= [1, 2, 1] <= [1, 3]`

That's accurate, yes.

> Similarly, we can also do `[1, 1] <= [1, 2, 1] <= [1, 2]`.

No, you can't. `[1, 2]` is less than `[1, 2, 1]`.

> So shouldn't `[1, 2]` match `[1, 2, 1]`?

I don't know what "match" means. There is exactly one value that is both less than or equal to **and** greater than or equal to `[1, 2]` and that's `[1, 2]`.

Sorry, I'm not sure where your confusion is, but if you have `x <= y` and `x >= y`, then it follows that `x == y`.

> Wasn't the intent here to get a prefix match?

What intent are you referring to exactly? I don't think you've told me what problem you're trying to solve, so I don't know how to tell what you're intent is.

If you want all keys with prefix `[x, y, z]`, then you can do `.ge(&[x, y, z]).le(&[x, y, z + 1])`. (With the caveat that is `z` is `255`, then you need `&[x, y+1]`, and so on.)

**Comment by yoursvivek** [comment]
>> Similarly, we can also do [1, 1] <= [1, 2, 1] <= [1, 2].

> No, you can't. [1, 2] is less than [1, 2, 1].

Mea culpa. This was the source of confusion. I should've paid attention that it's `Lexicographic ordering.` ;)

> If you want all keys with prefix [x, y, z], then you can do .ge(&[x, y, z]).le(&[x, y, z + 1]). (With the caveat that is z is 255, then you need &[x, y+1], and so on.)

I did exactly this. Closing this issue and thanks for your time.
