### ISSUE TITLE
add clone and len to MmapReadOnly

### ISSUE THREAD

**Issue by fulmicoton** [BurntSushi/fst#8]
MmapReadOnly exposes a range method that creates "free clones" of the mmap.
Could you add a len() and a clone() method?

**Comment by BurntSushi** [comment]
@fulmicoton Yes, I think that sounds OK. I'd take a PR, or I'll do it next time I get a chance.

**Comment by fulmicoton** [comment]
Thanks for the quick answer.

I'll send you a PR soon.

**Comment by BurntSushi** [comment]
Closed by 068a853f8956f3373815e3229108f2df65006edc
