### ISSUE TITLE
support for adding byte vector as value in map 

### ISSUE THREAD

**Issue by balajijinnah** [BurntSushi/fst#90]
It'll be very useful to store byte array as a value. 

I'm using fst in [Pathivu](https://github.com/pathivu/pathivu) for searching indexes. 

corresponding posting list for indexes is stored in rocksdb. 

It'll be very helpful, if the fst crate itself can store the posting list.

I'm willing to take this issue if it is accepted. But, need some mentoring.

**Comment by BurntSushi** [comment]
This was explored in this PR: https://github.com/BurntSushi/fst/pull/21

In general, the complexity such a change would add to this library is not something I'm willing to maintain.

Moreover, I think it would be highly unlikely to be a good idea to store a postings list in the fst. The room for compression is likely quite small and bloat the size of the FST making certain access patterns slower.
